# our final base image
FROM openjdk:21-jre-alpine

# set deployment directory
VOLUME /tmp

EXPOSE 8081

# copy over the built artifact from the maven image
ARG JAR_FILE=target/empresa-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} empresa-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=mysql","-jar","/empresa-0.0.1-SNAPSHOT.jar"]

# set the startup command to run your binary
CMD ["java", "-jar", "./empresa-0.0.1-SNAPSHOT.jar"]
