spring:
  application:
    name: qa+
  jpa:
    # Provide database platform that is being used
    hibernate:
      # New database is created when application starts and destroyed when application is stopped
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
  datasource:
    # URL connection to database (spring-security is database name)
    url: jdbc:mysql://
    # H2 sql Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
  h2:
    console:
      enabled: true
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always